

# Î¢ÐÅ¹«ÖÚºÅ
wechat:
  mpAppId: wx7a2096d334ecab96
  mpAppSecret: 89d1427a160fcfcbfcbda0abf4f9fee6
  mchId:
  mchKey:
  keyPath:
  notifyUrl:

projectUrl:
  wechatMpAuthorize: http://panyy.nat300.top
  wechatOpenAuthorize: http://panyy.nat300.top
  systemUrl:

spring:
  redis:
    host: 127.0.0.1
    port: 6379
